export const weatherStyleEmnu = {
  showBorder: false,
  BorderColor: '#000',
  BorderRaduis: 0,
  boxPadding: 0,
  showBackground: true,
  background: '#0054A3',
  containerStyle: '',

  updateTime: 6,

  showTemp: true,
  weatherContainerStyle: 'color: #ffffff',
  temmpNumberStyle: 'lineHeight: 50px;fontSize: 36px;fontFamily: PingFangSC',
  tempTextStyle: 'lineHeight: 33px;fontFamily: PingFangSC;fontSize: 24px;',
  tempImgWidth: '88px',
  tempImgHeight: '73px',
  tempRightStyle: 'marginLeft:30px',
  tempUnitStyle: 'lineHeight: 50px;fontSize:24px;fontFamily: PingFangSC;',

  showHum: true,
  humContainerStyle: 'color: #ffffff',
  humImgWidth: 65,
  humImgHeight: 86,
  humNumStyle: 'lineHeight: 50px;fontSize:36px;fontFamily: PingFangSC;',
  humTextStyle: 'lineHeight: 33px;fontSize:24px;fontFamily: PingFangSC;',
  humUnitStyle: 'lineHeight: 50px;fontSize:24px;fontFamily: PingFangSC;',
  humRightStyle: 'marginLeft:30px',

  showPM: true,
  PMContainerStyle: 'color: #ffffff',
  PMImgWidth: '86px',
  PMImgHeight: '66px',
  PMNumStyle: 'lineHeight: 50px;fontSize:36px;fontFamily: PingFangSC;',
  PMUnitStyle: 'lineHeight: 50px;fontSize:24px;fontFamily: PingFangSC;',
  PMTextStyle: 'lineHeight: 33px;fontSize:24px;fontFamily: PingFangSC;',
  PMRightStyle: 'marginLeft:30px',
};
