export default {
  dataSource: [
    {
      name: '数据中心-web',
      key: '/data-center',
      children: [
        {
          name: '房产',
          key: '/data-center/estate',
          url: 'https://3dl.dfocus.top/preview?pageId=11287&tagId=12',
          pageId: 11287,
          tagId: 12,
          height: 3166,
        },
        {
          name: '预算',
          key: '/data-center/bugdet',
          url: 'https://3dl.dfocus.top/preview?pageId=11283&tagId=12',
          pageId: 11283,
          tagId: 12,
          height: 1830,
        },
        {
          name: '周转房',
          key: '/data-center/zoom',
          url: 'https://3dl.dfocus.top/preview?pageId=11296&tagId=12',
          pageId: 11296,
          tagId: 12,
          height: 1710,
        },
      ],
    },
    {
      name: '数据中心-web(打包部署)',
      key: '/data-center-bale',
      children: [
        {
          name: '房产',
          key: '/data-center-bale/estate',
          url: 'https://3dl.dfocus.top/dp?pageId=11287&tagId=12',
          pageId: 11287,
          tagId: 12,
          height: 3166,
        },
        {
          name: '预算',
          key: '/data-center-bale/bugdet',
          url: 'https://3dl.dfocus.top/dp?pageId=11283&tagId=12',
          pageId: 11283,
          tagId: 12,
          height: 1830,
        },
        {
          name: '周转房',
          key: '/data-center-bale/zoom',
          url: 'https://3dl.dfocus.top/dp?pageId=11296&tagId=12',
          pageId: 11296,
          tagId: 12,
          height: 1710,
        },
      ],
    },
    {
      name: '数据中心-web(生产)',
      key: '/data-center-prod',
      children: [
        {
          name: '房产',
          key: '/data-center-prod/estate',
          prefixUrl: 'https://dfocus.fam.dfocus.co/fam-screen-data/preview?pageId=11287&tagId=12',
          pageId: 11287,
          tagId: 12,
          height: 3166,
        },
        {
          name: '预算',
          key: '/data-center-prod/bugdet',
          prefixUrl: 'https://dfocus.fam.dfocus.co/fam-screen-data/preview?pageId=11283&tagId=12',
          pageId: 11283,
          tagId: 12,
          height: 1830,
        },
        {
          name: '周转房',
          key: '/data-center-prod/zoom',
          prefixUrl: 'https://dfocus.fam.dfocus.co/fam-screen-data/preview?pageId=11296&tagId=12',
          pageId: 11296,
          tagId: 12,
          height: 1710,
        },
      ],
    },
    {
      name: 'FM 报表',
      key: '/fm-web-analysis',
      children: [
        {
          name: '设备运营分析',
          key: '/fm-web-analysis/equipment',
          url: 'https://3dl.dfocus.top/preview?pageId=11435&tagId=27',
          pageId: 11435,
          tagId: 27,
          height: 1700,
        },
        {
          name: '预防性维护运营分析',
          key: '/fm-web-analysis/preventive',
          url: 'https://3dl.dfocus.top/preview?pageId=11436&tagId=27',
          pageId: 11436,
          tagId: 27,
          height: 1700,
        },
        {
          name: '服务中心运营分析',
          key: '/fm-web-analysis/service-centre',
          url: 'https://3dl.dfocus.top/preview?pageId=11438&tagId=27',
          pageId: 11438,
          tagId: 27,
          height: 1300,
        },
        {
          name: '巡检运营分析',
          key: '/fm-web-analysis/inspection',
          url: 'https://3dl.dfocus.top/preview?pageId=11439&tagId=27',
          pageId: 11439,
          tagId: 27,
          height: 2400,
        },
        {
          name: '工单运营分析',
          key: '/fm-web-analysis/work-order',
          url: 'https://3dl.dfocus.top/preview?pageId=11440&tagId=27',
          pageId: 11440,
          tagId: 27,
          height: 2000,
        },
      ],
    },
  ],
};
