export default {
  equList: [
    {
      equCode: '0268',
      equName: '21-2C',
      fault: 0, // 损坏
      idle: 12, // 空闲
      used: 20, // 使用
      row: 4, // 行
      column: 8, // 列
      boxInfo: [
        { doorNo: '001', doorStatus: '0' },
        { doorNo: '002', doorStatus: '0' },
        { doorNo: '003', doorStatus: '0' },
        { doorNo: '004', doorStatus: '0' },
        { doorNo: '005', doorStatus: '0' },
        { doorNo: '006', doorStatus: '1' },
        { doorNo: '007', doorStatus: '0' },
        { doorNo: '008', doorStatus: '0' },
        { doorNo: '009', doorStatus: '0' },
        { doorNo: '010', doorStatus: '1' },
        { doorNo: '011', doorStatus: '0' },
        { doorNo: '012', doorStatus: '0' },
        { doorNo: '013', doorStatus: '1' },
        { doorNo: '014', doorStatus: '1' },
        { doorNo: '015', doorStatus: '1' },
        { doorNo: '016', doorStatus: '0' },
        { doorNo: '017', doorStatus: '1' },
        { doorNo: '018', doorStatus: '0' },
        { doorNo: '019', doorStatus: '1' },
        { doorNo: '020', doorStatus: '1' },
        { doorNo: '021', doorStatus: '1' },
        { doorNo: '022', doorStatus: '1' },
        { doorNo: '023', doorStatus: '1' },
        { doorNo: '024', doorStatus: '1' },
        { doorNo: '025', doorStatus: '1' },
        { doorNo: '026', doorStatus: '1' },
        { doorNo: '027', doorStatus: '1' },
        { doorNo: '028', doorStatus: '1' },
        { doorNo: '029', doorStatus: '1' },
        { doorNo: '030', doorStatus: '1' },
        { doorNo: '031', doorStatus: '1' },
        { doorNo: '032', doorStatus: '1' },
      ],
    },
    {
      equCode: '0266',
      equName: '21-2A',
      fault: 0,
      idle: 32,
      used: 4,
      row: 4,
      column: 9,
      boxInfo: [
        { doorNo: '001', doorStatus: '0' },
        { doorNo: '002', doorStatus: '0' },
        { doorNo: '003', doorStatus: '0' },
        { doorNo: '004', doorStatus: '0' },
        { doorNo: '005', doorStatus: '0' },
        { doorNo: '006', doorStatus: '1' },
        { doorNo: '007', doorStatus: '0' },
        { doorNo: '008', doorStatus: '0' },
        { doorNo: '009', doorStatus: '0' },
        { doorNo: '010', doorStatus: '0' },
        { doorNo: '011', doorStatus: '1' },
        { doorNo: '012', doorStatus: '0' },
        { doorNo: '013', doorStatus: '0' },
        { doorNo: '014', doorStatus: '1' },
        { doorNo: '015', doorStatus: '0' },
        { doorNo: '016', doorStatus: '0' },
        { doorNo: '017', doorStatus: '0' },
        { doorNo: '018', doorStatus: '0' },
        { doorNo: '019', doorStatus: '0' },
        { doorNo: '020', doorStatus: '0' },
        { doorNo: '021', doorStatus: '1' },
        { doorNo: '022', doorStatus: '0' },
        { doorNo: '023', doorStatus: '0' },
        { doorNo: '024', doorStatus: '0' },
        { doorNo: '025', doorStatus: '0' },
        { doorNo: '026', doorStatus: '0' },
        { doorNo: '027', doorStatus: '0' },
        { doorNo: '028', doorStatus: '0' },
        { doorNo: '029', doorStatus: '0' },
        { doorNo: '030', doorStatus: '0' },
        { doorNo: '031', doorStatus: '0' },
        { doorNo: '032', doorStatus: '0' },
        { doorNo: '033', doorStatus: '0' },
        { doorNo: '034', doorStatus: '0' },
        { doorNo: '035', doorStatus: '0' },
        { doorNo: '036', doorStatus: '0' },
      ],
    },
    {
      equCode: '0267',
      equName: '21-2B',
      fault: 0,
      idle: 21,
      used: 3,
      row: 4,
      column: 6,
      boxInfo: [
        { doorNo: '001', doorStatus: '0' },
        { doorNo: '002', doorStatus: '1' },
        { doorNo: '003', doorStatus: '0' },
        { doorNo: '004', doorStatus: '1' },
        { doorNo: '005', doorStatus: '0' },
        { doorNo: '006', doorStatus: '1' },
        { doorNo: '007', doorStatus: '0' },
        { doorNo: '008', doorStatus: '0' },
        { doorNo: '009', doorStatus: '0' },
        { doorNo: '010', doorStatus: '0' },
        { doorNo: '011', doorStatus: '0' },
        { doorNo: '012', doorStatus: '0' },
        { doorNo: '013', doorStatus: '0' },
        { doorNo: '014', doorStatus: '0' },
        { doorNo: '015', doorStatus: '0' },
        { doorNo: '016', doorStatus: '0' },
        { doorNo: '017', doorStatus: '0' },
        { doorNo: '018', doorStatus: '0' },
        { doorNo: '019', doorStatus: '0' },
        { doorNo: '020', doorStatus: '0' },
        { doorNo: '021', doorStatus: '0' },
        { doorNo: '022', doorStatus: '0' },
        { doorNo: '023', doorStatus: '0' },
        { doorNo: '024', doorStatus: '0' },
      ],
    },
  ],
  sumDoor: 92,
  sumIdleDoor: 65,
};
