export const popoverPositionList = [
  'topLeft',
  'top',
  'topRight',
  'tightTop',
  'right',
  'rightBottom',
  'bottomRight',
  'bottom',
  'bottomLeft',
  'leftBottom',
  'left',
  'leftTop',
];

const styles = {
  1: {
    cardBgColor: '#ffffff',
    borderRadius: 4,
    cardBorderColor: '#F0F1F5',
    showBoxShadow: true,
    hShadow: 1,
    vShadow: 1,
    blur: 10,
    spread: 0,
    shadowColor: '#d9dcdf',

    showTitle: true,
    title: '我是标题',
    headHeight: 45,
    headBgcolor: '#ffffff',
    headPadding: 30,
    headFontSize: 16,
    headFontWeight: 400,
    headFontColor: '#606060',
    headBorderWidth: 1,
    headBorderStyle: 'solid',
    headBorderColor: '#F0F1F5',
    titleTextAlign: 'left',

    showMore: false,
    moreBtnRight: 15,
    moreBtnWidth: 20,
    moreBtnHeight: 20,
    moreBtnRadius: 4,
    moreBtnBorderWidth: 1,
    moreBtnBorderColor: '#F0F1F5',
    moreBtnBgColor: '#f3f3fb',
    popoverPosition: 'bottom',
    popoverContentList: [],
  },
};
